#! /bin/sh

bspc config ignore_ewmh_struts true
xbindkeys -f $HOME/.config/bspwm/xbindkeysrc&
$HOME/.fehbg
lemonbar.sh&
#tint2&
picom&
upower.sh&
xbacklight -set 30
unclutter -root -not Minecraft -idle 5&
stalonetray&

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color "#000000"
bspc config normal_border_color "#e5e5e5"

bspc config border_width         1
bspc config window_gap          18

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier "mod1"
bspc config top_padding 0
bspc config border_radius 10
bspc rule -a feh state=floating
