#! /bin/sh
#bspc config ignore_ewmh_struts true
xrandr --output HDMI2 --mode 1920x1080 --rate 60.00 --output eDP1 --mode 1920x1080 --rate 60.05 --left-of HDMI2
pgrep xbindkeys || xbindkeys -f $HOME/.config/bspwm/xbindkeysrc&
#$HOME/.fehbg
hsetroot -solid '#31363b'
pgrep picom || picom&
pgrep upower.sh || upower.sh&
pgrep mpd || mpd&
pgrep unclutter || unclutter -root -not Minecraft -idle 5&
xbacklight -set 30
xset m 20/10 4

bspc monitor eDP1 -d I II III IV V 
bspc monitor HDMI2 -d VI VII VIII IX X

bspc config focused_border_color "#000000"
bspc config normal_border_color "#e5e5e5"

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier "mod1"
bspc config top_padding 0
bspc config border_radius 0
bspc rule -a feh state=floating
bspc rule -a Qemu-system-x86_64 state=floating rectangle=720x424+600+328
bspc rule -a Tint2 layer=BELOW manage=on border=off rectangle=33x1080+1920+0

tint2
